RTT Disconnect addition
getbraincloud/braincloud-cpp pull request #159
Opened 2020-12-09 13:37 UTC by pascalf1309

2020-12-09 13:41 UTC, Daivuk commented
Can you put the JIRA # in the title. I am unsure what this relates to

2020-12-10 14:38 UTC, davidstl requested changes
Looks good. Minor changes 🚲 required.
I presume this is not tested? I think it's very hard to repro case. So as long as other tests are still passing and C++ apps.

2020-12-10 14:38 UTC, davidstl commented on src/RTTComms.cpp
> +            if(_disconnectedWithReason==true)
🚲 
`if (_disconnectedWithReason == true)`

2020-12-10 14:38 UTC, davidstl commented on src/RTTComms.cpp
> +            if (operation == "DISCONNECT")
`else if`
We don't want to be comparing another string if first `if` passed.

2020-12-10 14:38 UTC, davidstl commented on src/RTTComms.cpp
> +			    _msg["reasonCode"] = _disconnectReasonCode;
🚲 
Replace tabs with spaces

2020-12-10 14:38 UTC, davidstl commented on src/RTTComms.cpp
> +                printf(output.c_str());
I think we wanted to do more than just print it out? I don't remember. Don't want this to be sent to _connectCallback failure?

But at least the user will have log. So leave it like that, we're good. This is a very rare case anyway.

2020-12-17 14:17 UTC, merged